# Generated by Django 5.2.5 on 2025-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("blood_group", models.CharField(max_length=3)),
                ("contact", models.CharField(max_length=50)),
                ("last_donation", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("blood_group_needed", models.CharField(max_length=3)),
                ("urgency", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=50)),
            ],
        ),
    ]
